name: pyro-annotator
services:
  # PostgreSQL database
  postgres:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dummy_pg_user
      - POSTGRES_PASSWORD=dummy_pg_pwd
      - POSTGRES_DB=dummy_pg_db
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U dummy_pg_user -d dummy_pg_db'"]
      interval: 10s
      timeout: 20s
      retries: 10

  # LocalStack S3 service
  localstack:
    image: localstack/localstack:1.4.0
    ports:
      - "4566:4566"
    environment:
      - EDGE_PORT=4566
      - SERVICES=s3
      - PERSISTENCE=1
    volumes:
      - ./annotation_api/scripts/localstack:/etc/localstack/init/ready.d
      - localstack_data:/var/lib/localstack
    healthcheck:
      test: ["CMD-SHELL", "awslocal --endpoint-url=http://localhost:4566 s3 ls s3://admin"]
      interval: 10s
      timeout: 20s
      retries: 10

  # Annotation API backend
  annotation_api:
    build:
      context: ./annotation_api
      dockerfile: ./Dockerfile
      tags:
        - "pyronear/annotation-api:latest"
    depends_on:
      postgres:
        condition: service_healthy
      localstack:
        condition: service_healthy
    ports:
      - "5050:5050"
    environment:
      - SUPPORT_EMAIL=contact@pyronear.org
      # DB
      - POSTGRES_URL=postgresql+asyncpg://dummy_pg_user:dummy_pg_pwd@postgres/dummy_pg_db
      # S3
      - S3_ENDPOINT_URL=http://localstack:4566
      - S3_ACCESS_KEY=fake
      - S3_SECRET_KEY=fake
      - S3_REGION=us-east-1
      - S3_PROXY_URL=http://localhost:4566
      # Authentication
      - AUTH_USERNAME=admin
      - AUTH_PASSWORD=admin12345
      - JWT_SECRET=your_jwt_secret_key_change_in_production_please
      - ACCESS_TOKEN_EXPIRE_HOURS=24
    restart: unless-stopped
    command: "sh -c 'python app/db.py && uvicorn app.main:app --host 0.0.0.0 --port 5050 --proxy-headers'"
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:5050/status"]
      interval: 10s
      timeout: 20s
      retries: 10

  # Frontend React application
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL}
        - VITE_ENVIRONMENT=production
      tags:
        - "pyronear/annotation-app:latest"
    depends_on:
      annotation_api:
        condition: service_healthy
    ports:
      - "3000:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data:
  localstack_data:
