"""initial

Revision ID: 063dc76c9846
Revises: 
Create Date: 2026-05-01 05:12:09.152220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '063dc76c9846'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sequences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_api', sa.Enum('PYRONEAR_FRENCH_API', 'ALERT_WILDFIRE', 'CENIA', name='sourceapi'), nullable=False),
    sa.Column('alert_api_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('camera_name', sa.String(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('azimuth', sa.Integer(), nullable=True),
    sa.Column('is_wildfire_alertapi', sa.Enum('WILDFIRE_SMOKE', 'OTHER_SMOKE', 'OTHER', name='annotationtype'), nullable=True),
    sa.Column('organisation_name', sa.String(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alert_api_id', 'source_api', name='uq_sequence_alert_source')
    )
    op.create_index('ix_sequence_camera_id', 'sequences', ['camera_id'], unique=False)
    op.create_index('ix_sequence_camera_name', 'sequences', ['camera_name'], unique=False)
    op.create_index('ix_sequence_camera_org', 'sequences', ['camera_name', 'organisation_name'], unique=False)
    op.create_index('ix_sequence_created_at', 'sequences', ['created_at'], unique=False)
    op.create_index('ix_sequence_full_filter', 'sequences', ['source_api', 'camera_name', 'organisation_name', 'is_wildfire_alertapi'], unique=False)
    op.create_index('ix_sequence_is_wildfire', 'sequences', ['is_wildfire_alertapi'], unique=False)
    op.create_index('ix_sequence_last_seen_at', 'sequences', ['last_seen_at'], unique=False)
    op.create_index('ix_sequence_organisation_id', 'sequences', ['organisation_id'], unique=False)
    op.create_index('ix_sequence_organisation_name', 'sequences', ['organisation_name'], unique=False)
    op.create_index('ix_sequence_recorded_at', 'sequences', ['recorded_at'], unique=False)
    op.create_index('ix_sequence_source_api', 'sequences', ['source_api'], unique=False)
    op.create_index('ix_sequence_source_camera', 'sequences', ['source_api', 'camera_name'], unique=False)
    op.create_index('ix_sequence_source_camera_org', 'sequences', ['source_api', 'camera_name', 'organisation_name'], unique=False)
    op.create_index('ix_sequence_source_camera_wildfire', 'sequences', ['source_api', 'camera_name', 'is_wildfire_alertapi'], unique=False)
    op.create_index('ix_sequence_source_org', 'sequences', ['source_api', 'organisation_name'], unique=False)
    op.create_index('ix_sequence_source_org_wildfire', 'sequences', ['source_api', 'organisation_name', 'is_wildfire_alertapi'], unique=False)
    op.create_index('ix_sequence_source_wildfire', 'sequences', ['source_api', 'is_wildfire_alertapi'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', name='uq_user_username')
    )
    op.create_index('ix_user_username', 'users', ['username'], unique=False)
    op.create_table('detections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('alert_api_id', sa.Integer(), nullable=False),
    sa.Column('sequence_id', sa.Integer(), nullable=True),
    sa.Column('bucket_key', sa.String(), nullable=False),
    sa.Column('algo_predictions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['sequence_id'], ['sequences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alert_api_id', 'id', name='uq_detection_alert_id')
    )
    op.create_index('ix_detection_created_at', 'detections', ['created_at'], unique=False)
    op.create_index('ix_detection_recorded_at', 'detections', ['recorded_at'], unique=False)
    op.create_index('ix_detection_sequence_created', 'detections', ['sequence_id', 'created_at'], unique=False)
    op.create_index('ix_detection_sequence_id', 'detections', ['sequence_id'], unique=False)
    op.create_table('sequences_annotations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sequence_id', sa.Integer(), nullable=True),
    sa.Column('has_smoke', sa.Boolean(), nullable=False),
    sa.Column('has_false_positives', sa.Boolean(), nullable=False),
    sa.Column('false_positive_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('smoke_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('has_missed_smoke', sa.Boolean(), nullable=False),
    sa.Column('is_unsure', sa.Boolean(), nullable=True),
    sa.Column('annotation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_stage', sa.Enum('IMPORTED', 'READY_TO_ANNOTATE', 'UNDER_ANNOTATION', 'SEQ_ANNOTATION_DONE', 'IN_REVIEW', 'NEEDS_MANUAL', 'ANNOTATED', name='sequenceannotationprocessingstage'), nullable=False),
    sa.ForeignKeyConstraint(['sequence_id'], ['sequences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sequence_id', name='uq_sequence_annotation_sequence_id')
    )
    op.create_index('ix_sequence_annotation_created_at', 'sequences_annotations', ['created_at'], unique=False)
    op.create_index('ix_sequence_annotation_fp_types', 'sequences_annotations', ['false_positive_types'], unique=False, postgresql_using='gin')
    op.create_index('ix_sequence_annotation_has_false_positives', 'sequences_annotations', ['has_false_positives'], unique=False)
    op.create_index('ix_sequence_annotation_has_missed_smoke', 'sequences_annotations', ['has_missed_smoke'], unique=False)
    op.create_index('ix_sequence_annotation_has_smoke', 'sequences_annotations', ['has_smoke'], unique=False)
    op.create_index('ix_sequence_annotation_is_unsure', 'sequences_annotations', ['is_unsure'], unique=False)
    op.create_index('ix_sequence_annotation_processing_stage', 'sequences_annotations', ['processing_stage'], unique=False)
    op.create_index('ix_sequence_annotation_smoke_types', 'sequences_annotations', ['smoke_types'], unique=False, postgresql_using='gin')
    op.create_index('ix_sequence_annotation_stage_date', 'sequences_annotations', ['processing_stage', 'created_at'], unique=False)
    op.create_table('detections_annotations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('detection_id', sa.Integer(), nullable=True),
    sa.Column('annotation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processing_stage', sa.Enum('IMPORTED', 'VISUAL_CHECK', 'BBOX_ANNOTATION', 'ANNOTATED', name='detectionannotationprocessingstage'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['detection_id'], ['detections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('detection_id', name='uq_detection_annotation_detection_id')
    )
    op.create_index('ix_detection_annotation_created_at', 'detections_annotations', ['created_at'], unique=False)
    op.create_index('ix_detection_annotation_detection_date', 'detections_annotations', ['detection_id', 'created_at'], unique=False)
    op.create_index('ix_detection_annotation_processing_stage', 'detections_annotations', ['processing_stage'], unique=False)
    op.create_index('ix_detection_annotation_stage_date', 'detections_annotations', ['processing_stage', 'created_at'], unique=False)
    op.create_table('sequence_annotation_contributions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sequence_annotation_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('contributed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sequence_annotation_id'], ['sequences_annotations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_seq_contrib_annotation_user', 'sequence_annotation_contributions', ['sequence_annotation_id', 'user_id'], unique=False)
    op.create_index('ix_seq_contrib_user_time', 'sequence_annotation_contributions', ['user_id', 'contributed_at'], unique=False)
    op.create_table('detection_annotation_contributions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('detection_annotation_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('contributed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['detection_annotation_id'], ['detections_annotations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_det_contrib_annotation_user', 'detection_annotation_contributions', ['detection_annotation_id', 'user_id'], unique=False)
    op.create_index('ix_det_contrib_user_time', 'detection_annotation_contributions', ['user_id', 'contributed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_det_contrib_user_time', table_name='detection_annotation_contributions')
    op.drop_index('ix_det_contrib_annotation_user', table_name='detection_annotation_contributions')
    op.drop_table('detection_annotation_contributions')
    op.drop_index('ix_seq_contrib_user_time', table_name='sequence_annotation_contributions')
    op.drop_index('ix_seq_contrib_annotation_user', table_name='sequence_annotation_contributions')
    op.drop_table('sequence_annotation_contributions')
    op.drop_index('ix_detection_annotation_stage_date', table_name='detections_annotations')
    op.drop_index('ix_detection_annotation_processing_stage', table_name='detections_annotations')
    op.drop_index('ix_detection_annotation_detection_date', table_name='detections_annotations')
    op.drop_index('ix_detection_annotation_created_at', table_name='detections_annotations')
    op.drop_table('detections_annotations')
    op.drop_index('ix_sequence_annotation_stage_date', table_name='sequences_annotations')
    op.drop_index('ix_sequence_annotation_smoke_types', table_name='sequences_annotations', postgresql_using='gin')
    op.drop_index('ix_sequence_annotation_processing_stage', table_name='sequences_annotations')
    op.drop_index('ix_sequence_annotation_is_unsure', table_name='sequences_annotations')
    op.drop_index('ix_sequence_annotation_has_smoke', table_name='sequences_annotations')
    op.drop_index('ix_sequence_annotation_has_missed_smoke', table_name='sequences_annotations')
    op.drop_index('ix_sequence_annotation_has_false_positives', table_name='sequences_annotations')
    op.drop_index('ix_sequence_annotation_fp_types', table_name='sequences_annotations', postgresql_using='gin')
    op.drop_index('ix_sequence_annotation_created_at', table_name='sequences_annotations')
    op.drop_table('sequences_annotations')
    op.drop_index('ix_detection_sequence_id', table_name='detections')
    op.drop_index('ix_detection_sequence_created', table_name='detections')
    op.drop_index('ix_detection_recorded_at', table_name='detections')
    op.drop_index('ix_detection_created_at', table_name='detections')
    op.drop_table('detections')
    op.drop_index('ix_user_username', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_sequence_source_wildfire', table_name='sequences')
    op.drop_index('ix_sequence_source_org_wildfire', table_name='sequences')
    op.drop_index('ix_sequence_source_org', table_name='sequences')
    op.drop_index('ix_sequence_source_camera_wildfire', table_name='sequences')
    op.drop_index('ix_sequence_source_camera_org', table_name='sequences')
    op.drop_index('ix_sequence_source_camera', table_name='sequences')
    op.drop_index('ix_sequence_source_api', table_name='sequences')
    op.drop_index('ix_sequence_recorded_at', table_name='sequences')
    op.drop_index('ix_sequence_organisation_name', table_name='sequences')
    op.drop_index('ix_sequence_organisation_id', table_name='sequences')
    op.drop_index('ix_sequence_last_seen_at', table_name='sequences')
    op.drop_index('ix_sequence_is_wildfire', table_name='sequences')
    op.drop_index('ix_sequence_full_filter', table_name='sequences')
    op.drop_index('ix_sequence_created_at', table_name='sequences')
    op.drop_index('ix_sequence_camera_org', table_name='sequences')
    op.drop_index('ix_sequence_camera_name', table_name='sequences')
    op.drop_index('ix_sequence_camera_id', table_name='sequences')
    op.drop_table('sequences')
    # ### end Alembic commands ###

    # Drop enum types created implicitly by sa.Enum columns above.
    bind = op.get_bind()
    for enum_name in (
        'detectionannotationprocessingstage',
        'sequenceannotationprocessingstage',
        'annotationtype',
        'sourceapi',
    ):
        postgresql.ENUM(name=enum_name).drop(bind, checkfirst=True)
