name: pyro-label
services:
  db:
    image: postgres:15-alpine
    expose:
      - 5432
    environment:
      - POSTGRES_USER=dummy_pg_user
      - POSTGRES_PASSWORD=dummy_pg_pwd
      - POSTGRES_DB=dummy_pg_db
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U dummy_pg_user -d dummy_pg_db'"]
      interval: 10s
      timeout: 20s
      retries: 10

  # ref link: https://github.com/localstack/localstack/blob/master/docker-compose.yml
  localstack:
    image: localstack/localstack:1.4.0
    ports:
      - 4566:4566
    # environment variables details: https://docs.localstack.cloud/references/configuration/
    environment:
      - EDGE_PORT=4566
      - SERVICES=s3
    volumes:
      - ./scripts/localstack:/etc/localstack/init/ready.d
    healthcheck:
      test: ["CMD-SHELL", "awslocal --endpoint-url=http://localhost:4566 s3 ls s3://admin"]
      interval: 10s
      timeout: 20s
      retries: 10

  backend:
    image: heartexlabs/label-studio:latest
    depends_on:
      db:
        condition: service_healthy
      localstack:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - POSTGRE_NAME=dummy_pg_db
      - POSTGRE_USER=dummy_pg_user
      - POSTGRE_PASSWORD=dummy_pg_pwd
      - POSTGRE_PORT=5432
      - POSTGRE_HOST=db
      - DJANGO_DB=default
      - S3_ENDPOINT_URL=http://localstack:4566
      - S3_ACCESS_KEY=fake
      - S3_SECRET_KEY=fake
      - S3_REGION=us-east-1
    volumes:
      - ./mydata:/label-studio/data

