name: Annotation API CI

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'annotation_api/**'
      - '.github/workflows/annotation-api-ci.yml'

defaults:
  run:
    working-directory: annotation_api

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Pre-build backend image with cache
      uses: docker/build-push-action@v5
      with:
        context: annotation_api
        file: annotation_api/Dockerfile
        target: test
        tags: pyronear/annotation-api:test
        load: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Cache Docker images
      uses: actions/cache@v3
      with:
        path: /tmp/docker-images
        key: docker-images-${{ runner.os }}-${{ hashFiles('annotation_api/docker-compose-dev.yml') }}
        restore-keys: |
          docker-images-${{ runner.os }}-
    
    - name: Load cached Docker images
      run: |
        if [ -d /tmp/docker-images ]; then
          for img in /tmp/docker-images/*.tar; do
            [ -f "$img" ] && docker load -i "$img" || true
          done
        fi
    
    - name: Pull and save base images
      run: |
        mkdir -p /tmp/docker-images
        
        # Pull images if not already present
        docker pull postgres:15-alpine || true
        docker pull localstack/localstack:1.4.0 || true
        
        # Save images for next run
        docker save postgres:15-alpine -o /tmp/docker-images/postgres.tar || true
        docker save localstack/localstack:1.4.0 -o /tmp/docker-images/localstack.tar || true
    
    - name: Run tests using make
      run: |
        # Use the pre-built image by tagging it appropriately
        docker tag pyronear/annotation-api:test pyronear/annotation-api:latest || true
        
        # Run the tests
        make test