name: Ruff Check - annotation_api

on:
  pull_request:
    paths:
      - 'annotation_api/**'
    branches:
      - '**'

jobs:
  ruff-check:
    name: Run ruff check on annotation_api
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          
      - name: Install dependencies
        working-directory: annotation_api
        run: uv sync --group dev
        
      - name: Run ruff check
        working-directory: annotation_api
        run: uv run ruff check .